version: "3.7"
services:
  gateway:
    image: node:alpine
    container_name: gateway-rabbitmq
    environment:
      - NODE_ENV=development
    build: .
    working_dir: /app
    command: npm run start:debug
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/app

networks:
  default:
    external: true
    name: node-rabbitmq_pingpong
