version: "3.7"
services:
  gateway:
    image: node:latest
    container_name: balamu-gateway
    environment:
      - NODE_ENV=development
    build: .
    working_dir: /app
    command: npm run start:debug
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/app

networks:
  default:
    external: true
    name: balamu
